- name: Install NGINX for reverse proxy
  apt:
    name: nginx
    state: present

- name: Reverse proxy conf
  copy:
    dest: /etc/nginx/sites-available/reverse-proxy
    content: |
      upstream web1 {
          server 127.0.0.1:8082;
      }
      upstream pihole {
          server 127.0.0.1:8081;
      }
      server {
          listen 80;
          server_name nginx.ec.com;
          location / {
              proxy_pass http://web1;
          }
      }
      server {
          listen 80;
          server_name pihole.ec.com;
          location / {
              proxy_pass http://pihole;
          }
      }

- name: Copier la conf NGINX
  file:
    src: /etc/nginx/sites-available/reverse-proxy
    dest: /etc/nginx/sites-enabled/reverse-proxy
    state: link

- name: Supprimer le site NGINX par défaut 
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Restart NGINX
  service:
    name: nginx
    state: restarted