- name: Create Pi-hole container
  docker_container:
    name: pihole
    image: pihole/pihole:latest
    state: started
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80"
      - "443:443"
    environment:
      TZ: 'Europe/Paris'
    volumes:
      - "/etc/pihole:/etc/pihole"
      - "/etc/dnsmasq.d:/etc/dnsmasq.d"