- name: install iptables-persistent
  apt:
    name: iptables-persistent
    state: present

- name: Autoriser les connexions SSH
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    jump: ACCEPT

- name: Autoriser les connexions HTTP
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 80
    jump: ACCEPT

- name: Autoriser les connexions HTTPS
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 443
    jump: ACCEPT

- name: Autoriser ce qui vient du réseau local
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    source: 192.168.10.1/24
    jump: ACCEPT

- name: Autoriser les sorties type SSH
  iptables:
    chain: OUTPUT
    protocol: tcp
    destination_port: 22
    jump: ACCEPT

- name: icmp accept 
  iptables:
    chain: INPUT
    protocol: icmp
    jump: ACCEPT

- name: icmp accept
  iptables:
    chain: OUTPUT
    protocol: icmp
    jump: ACCEPT

- name: Autoriser les connexions UDP
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 53
    jump: ACCEPT

- name: Autoriser les connexions UDP
  iptables:
    chain: INPUT
    protocol: udp
    destination_port: 53
    jump: ACCEPT

- name: Ensure the iptables NAT rule for TCP is present for DNS
  iptables:
    table: nat
    chain: PREROUTING 
    protocol: tcp
    destination_port: 53
    jump: DNAT
    to_destination: 0.0.0.0:8053
 
- name: Ensure the iptables NAT rule for UDP is present for DNS
  iptables:
    table: nat
    chain: PREROUTING 
    protocol: udp
    destination_port: 53
    jump: DNAT
    to_destination: 0.0.0.0:8053

- name: SMTP entrant
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 993
    jump: ACCEPT

- name: SMTP sortant
  iptables:
    chain: OUTPUT
    protocol: tcp
    destination_port: 465
    jump: ACCEPT

- name: Refuser les autres connexions en INPUT
  iptables:
    chain: INPUT
    policy: DROP

- name: Refuser les autres connexions en FORWARD
  iptables:
    chain: FORWARD
    policy: DROP

- name: Sauvegarder les règles iptables
  shell: iptables-save > /etc/iptables/rules.v4
