- name: Ensure Docker is installed
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Ensure Docker is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Pull Nginx image
  docker_image:
    name: nginx
    source: pull

- name: Run Nginx container
  docker_container:
    name: nginx
    image: nginx
    state: started
    ports:
      - "80:80"
    restart_policy: always

#- name: Déployer le reverse proxy Nginx
#  docker_container:
#    name: nginx_reverse_proxy
#    image: nginx:latest
#    state: started
#    restart_policy: always
#    networks:
#      - name: webnet
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - /path/to/reverse_proxy/conf:/etc/nginx/conf.d
