---
- name: Déploiement SSH
  hosts: all
  become: yes
  tasks:
    - name: Génération de la clé
      openssh_keypair:
        path: /tmp/lisa
        type: rsa
        size: 4096
        state: present
        force: no
      delegate_to: localhost
      run_once: yes

    - name: Création de l'utilisateur test
      user:
        name: test
        shell: /bin/bash
        groups: sudo
        append: yes
        password: "{{ 'password' | password_hash('sha512') }}"
      become: yes

    - name: Déploiement de la clé SSH
      authorized_key: 
        user: test
        key: "{{ lookup('file', '/tmp/lisa.pub') }}"
        state: present
      become: yes

- name: Modification du hostname
  hosts: machine
  become: yes
  tasks:
    - name: Définir le nouveau hostname
      hostname:
        name: raspi

- name: Configuration du firewall
  hosts: machine
  become: yes
  tasks:
   - name: install iptables-persistent
     apt:
      name: iptables-persistent
      state: present
  
   - name: Autoriser les connexions SSH
     iptables:
       chain: INPUT
       protocol: tcp
       destination_port: 22
       jump: ACCEPT

   - name: Autoriser les connexions HTTP
     iptables:
       chain: INPUT
       protocol: tcp
       destination_port: 80
       jump: ACCEPT

   - name: Autoriser les connexions HTTPS
     iptables:
       chain: INPUT
       protocol: tcp
       destination_port: 443
       jump: ACCEPT
 
   - name: Autoriser ce qui vient du réseau local
     iptables:
       chain: INPUT
       protocol: tcp
       destination_port: 22
       source: 192.168.10.1/24
       jump: ACCEPT
 
   - name: Autoriser les sorties type SSH
     iptables:
       chain: OUTPUT
       protocol: tcp
       destination_port: 22
       jump: ACCEPT

   - name: Autoriser les connexions établies et reliées
     iptables:
       chain: INPUT
       ctstate: ESTABLISHED,RELATED
       jump: ACCEPT
 
   - name: Autoriser les connexions établies et reliées
     iptables:
       chain: OUTPUT
       ctstate: ESTABLISHED,RELATED
       jump: ACCEPT

   - name: icmp accept
     iptables:
       chain: INPUT
       protocol: icmp
       jump: ACCEPT

   - name: icmp accept
     iptables:
       chain: OUTPUT
       protocol: icmp
       jump: ACCEPT


   - name: Refuser les autres connexions en INPUT
     iptables:
       chain: INPUT
       policy: DROP

   - name: Refuser les autres connexions en FORWARD
     iptables:
       chain: FORWARD
       policy: DROP

   - name: Sauvegarder les règles iptables
     shell: iptables-save > /etc/iptables/rules.v4

- name: Installation et configuration de Fail2ban
  hosts: machine
  become: yes
  tasks:
    - name: Installer Fail2ban
      apt:
        name: fail2ban
        state: present
        update_cache: yes

    - name: Assurer que le service Fail2ban est démarré et activé au démarrage
      service:
        name: fail2ban
        state: started
        enabled: yes

    - name: Configurer Fail2ban pour SSH, HTTP et HTTPS
      copy:
        dest: /etc/fail2ban/jail.local
        content: |
          [DEFAULT]
          bantime  = 600
          findtime  = 600
          maxretry = 3

          [sshd]
          enabled = true
          port    = ssh
          logpath = /var/log/auth.log
          backend = systemd

    - name: Redémarrer Fail2ban pour appliquer les nouvelles configurations
      service:
        name: fail2ban
        state: restarted