- name: Create a Docker network
  docker_network:
    name: docker_network
    enable_ipv6: yes
    driver: bridge
    ipam_config:
      - subnet: 192.168.1.0/16
        gateway: 192.168.1.1
      - subnet: "2001:db8:1::/64"
        gateway: "2001:db8:1::1"

- name: Pull Nginx image
  docker_image:
    name: nginx
    source: pull

- name: Run Nginx container
  docker_container:
    name: nginx
    image: nginx
    networks:
      - name: docker_network
        ipv4_address: 192.168.1.3
        ipv6_address: 2001:db8:1::3
    state: started
    ports:
      - "8082:80"
    restart_policy: always
